title: Anthony Isaac Ayon # your name (or website title) here
logo: "images/paris_pic.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent graduate with a bachelor’s degree in Cognitive Science specialized in Machine Learning and Neural Computation.
  <br><br>
  <a href="https://www.linkedin.com/in/anthony-ayon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
